id: P04B0707B
initial_creation_type: input
source_metadata:
  title: Katok Getse Gyurme Tenpa Gyaltsen
  language: bo
  description: 'Texts by and about Katok Getse Gyurme Tenpa Gyaltsen (kaḥ thog dge
    rtse ''gyur med bstan pa rgyal mtshan, 1954–2018), who was the seventh head of
    the Nyingma tradition:'
  volume:
    edc45dc8ae6a43d0b139abab23cdfe11:
      title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
      parent: Aspiration Prayers
created_at: '2022-03-01T00:14:01.759289'
last_modified_at: '2022-03-01T00:14:01.759292'
